env:
  - PROTOBUF_VERSION=2.6.1
  - PROTOBUF_VERSION=3.0.0-alpha-2

language: rust

rust:
  - nightly

before_install:
  - sudo -E ./install-protobuf.sh
  - protoc --version

script:
  # Full rebuild with regenerate
  - src/full-rebuild.sh
  # Test cargo configuration
  - cargo test
