language: rust

rust:
  - nightly

before_install:
  - sudo ./install-protobuf.sh
  - protoc --version

script:
  # Full rebuild with regenerate
  - src/full-rebuild.sh
  # Test cargo configuration
  - cargo test
