[package]

name = "protobuf"
version = "0.0.1"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]

[lib]

name = "protobuf"
path = "src/lib/protobuf.rs"

[[bin]]

name = "protoc-gen-rust"
path = "src/protoc-gen-rust.rs"
test = false

[[bin]]

name = "rust-protobuf-perftest"
path = "src/perftest/perftest.rs"
test = false
