[package]
name = "bytes"
version = "0.1.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]

[dependencies]
protobuf = { path = "../../protobuf" }

[build-dependencies]
protoc-rust = { path = "../../protoc-rust" }
